### ISSUE TITLE
TODO and bugs

### ISSUE THREAD

**Issue by lgatto** [SpatialMap/SpatialMapDev#12]
## Improvement 
- [ ] Remove the exprs data from the table
- [ ] Add axes on the PCA plot
- [ ] Either remove the t-SNE tab or add the plot
- [ ] Make line profile axes label smaller
- [ ] Line profiles scaling
- [ ] Make protein labels/names bigger on plot (currently unreadable)

## Bugs
- [ ] Line profiles don't show up in the `hyperLOPIT` data

**Comment by Kohze** [comment]
Good points, will add them later today

**Comment by Kohze** [comment]
http://prntscr.com/gqar8e

The profile plot is now scaled to the absolute 0-1 scale. Regarding  "Make line profile axes label smaller" I was thinking if we actually needed the axis labeling on each line. Otherwise i would suggest to leave only scaling numbers on the most left one (all the others just as lines + channel name).
